%{"account_balance" => 0, "created" => 1533092213, "currency" => nil,
  "default_source" => "card_1CuAW1J1Re7kKO1MzzVdrdj1", "delinquent" => false,
  "description" => nil, "discount" => nil, "email" => "stripetest2@gmail.com",
  "id" => "cus_DKqCFHfDwQpGOO", "invoice_prefix" => "601DE2A",
  "livemode" => false, "metadata" => %{"name" => "Test Name 1"},
  "object" => "customer", "shipping" => nil,
  "sources" => %{
    "data" => [%{
      "address_city" => nil,
      "address_country" => nil,
       "address_line1" => nil,
       "address_line1_check" => nil,
       "address_line2" => nil,
       "address_state" => nil,
       "address_zip" => "94612",
       "address_zip_check" => "pass",
       "brand" => "Visa", "country" => "US",
       "customer" => "cus_DKqCFHfDwQpGOO",
       "cvc_check" => "pass",
       "dynamic_last4" => nil,
       "exp_month" => 1, 
       "exp_year" => 2019,
       "fingerprint" => "qO9nK3Pu4g9CQvPR",
       "funding" => "credit",
       "id" => "card_1CuAW1J1Re7kKO1MzzVdrdj1",
       "last4" => "0077",
       "metadata" => %{},
       "name" => "stripetest2@gmail.com",
       "object" => "card",
       "tokenization_method" => nil}],
       "has_more" => false,
       "object" => "list",
    "total_count" => 1, "url" => "/v1/customers/cus_DKqCFHfDwQpGOO/sources"},
  "subscriptions" => %{"data" => [], "has_more" => false, "object" => "list",
    "total_count" => 0,
    "url" => "/v1/customers/cus_DKqCFHfDwQpGOO/subscriptions"}}
